DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL,
    pass VARCHAR(250) NOT NULL
);